image: persoff68/alpine-openjdk-13-glibc

variables:
  MAVEN_CLI_OPTS: "-ntp --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - analyze

maven-build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS compile $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-test:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

sonar-analyze:
  stage: analyze
  dependencies:
    - maven-test
  script:
    - ./mvnw $MAVEN_CLI_OPTS initialize sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day
