image: persoff68/alpine-openjdk-13-glibc

variables:
  MAVEN_CLI_OPTS: "-ntp --batch-mode -s settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - analyze
  - deploy

maven-build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS compile $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-test:
  stage: test
  dependencies:
    - maven-build
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

sonar-analyze:
  stage: analyze
  dependencies:
    - maven-test
  script:
    - ./mvnw $MAVEN_CLI_OPTS initialize sonar:sonar $MAVEN_OPTS
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
  artifacts:
    paths:
      - target/
    expire_in: 1 day

deploy-to-rerpository:
  stage: deploy
  dependencies:
    - maven-build
  script:
    - ./mvnw $MAVEN_CLI_OPTS deploy $MAVEN_OPTS -Dmaven.test.skip=true
      -Dmaven.repo.url=$MAVEN_URL
      -Dmaven.repo.username=$MAVEN_USERNAME
      -Dmaven.repo.password=$MAVEN_PASSWORD
  artifacts:
    paths:
      - target/
    expire_in: 1 day

