image: persoff68/alpine-openjdk-15-glibc

variables:
  MAVEN_CLI_OPTS: "-ntp --batch-mode -s etc/maven/settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - .sonar/cache/

stages:
  - build
  - UT
  - IT
  - analyze
  - deploy

compile:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS compile $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

unit-tests:
  stage: UT
  dependencies:
    - compile
  script:
    - ./mvnw $MAVEN_CLI_OPTS test $MAVEN_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 1 day

integration-tests:
  stage: IT
  dependencies:
    - compile
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify $MAVEN_OPTS
      -DskipUTs
  artifacts:
    paths:
      - target/
    expire_in: 1 day

contract-tests:
  stage: IT
  dependencies:
    - compile
  script:
    - ./mvnw $MAVEN_CLI_OPTS initialize test-compile failsafe:integration-test failsafe:verify $MAVEN_OPTS
      -Pcontracts
      -Dmaven.repo.url=$MAVEN_URL
      -Dmaven.repo.username=$MAVEN_USERNAME
      -Dmaven.repo.password=$MAVEN_PASSWORD
  artifacts:
    paths:
      - target/
    expire_in: 1 day

sonar:
  stage: analyze
  dependencies:
    - unit-tests
    - integration-tests
  script:
    - ./mvnw $MAVEN_CLI_OPTS initialize sonar:sonar $MAVEN_OPTS
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
  artifacts:
    paths:
      - target/
    expire_in: 1 day

checkstyle:
  stage: analyze
  script:
    - ./mvnw $MAVEN_CLI_OPTS checkstyle:check $MAVEN_OPTS

deploy-to-repo:
  stage: deploy
  dependencies:
    - compile
  script:
    - ./mvnw $MAVEN_CLI_OPTS deploy $MAVEN_OPTS
      -Dmaven.test.skip=true
      -Dmaven.repo.url=$MAVEN_URL
      -Dmaven.repo.username=$MAVEN_USERNAME
      -Dmaven.repo.password=$MAVEN_PASSWORD
  artifacts:
    paths:
      - target/
    expire_in: 1 day
