package com.persoff68.fatodo.model.constant;

public enum PushNotificationType {
    ITEM_CREATE, ITEM_GROUP_CREATE, ITEM_MEMBER_ADD,
    CHAT_CREATE, CHAT_MESSAGE_CREATE, CHAT_REACTION_INCOMING,
    CONTACT_REQUEST_INCOMING, CONTACT_ACCEPT_OUTCOMING,
    COMMENT_CREATE, COMMENT_REACTION_INCOMING,
    REMINDER
}
